site_name: Run:AI Documentation Library
site_url: https://docs.run.ai/
copyright: Copyright © 2020 Run:AI
google_analytics:
  - UA-122651141-1
  - auto

repo_url: https://github.com/run-ai/docs/


docs_dir: docs
theme:
  name: material
  custom_dir: overrides
#  name: mkdocs
#  name: readthedocs
#  name: ivory
#  name: bootstrap4
#  name: gitbook
#  name: 'rtd-dropdown'
 # palette:
  #  scheme: slate
#     primary: indigo
#     accent: red
  # font:
  #   text: Roboto
  #   code: Roboto Mono
  language: en
  favicon: images/favicon.ico
  logo: images/runai-logo2.svg
  features:
    - navigation.tabs
extra_css:
  - stylesheets/extra.css
strict: true
plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'Administrator/Cluster-Setup/Run-AI-GPU-Cluster-Prerequisites.md': 'Administrator/Cluster-Setup/cluster-prerequisites.md'
        'Administrator/Cluster-Setup/Installing-Run-AI-on-an-on-premise-Kubernetes-Cluster.md' : 'Administrator/Cluster-Setup/cluster-install.md'
        'Administrator/Researcher-Setup/Installing-the-Run-AI-Command-Line-Interface.md' : 'Administrator/Researcher-Setup/cli-install.md'
        'Researcher/Walkthroughs/Walkthrough-Start-and-Use-Interactive-Build-Workloads-.md' : 'Researcher/Walkthroughs/walkthrough-build.md'
        'Researcher/Walkthroughs/Walkthrough-Launch-an-Interactive-Build-Workload-with-Connected-Ports.md' : 'Researcher/Walkthroughs/walkthrough-build-ports.md'
        'Researcher/Walkthroughs/Walkthrough-Launch-Unattended-Training-Workloads-.md' : 'Researcher/Walkthroughs/walkthrough-train.md'
        'Researcher/Walkthroughs/Walkthrough-Using-GPU-Fractions.md' : 'Researcher/Walkthroughs/walkthrough-fractions.md'
        'Administrator/Cluster-Setup/Deleting-Cluster-Install.md' : 'Administrator/Cluster-Setup/cluster-delete.md'
        'Administrator/Cluster-Setup/Upgrading-Cluster-Install.md' : 'Administrator/Cluster-Setup/cluster-upgrade.md'
        'Administrator/Researcher-Setup/Switch-from-working-with-Docker-to-working-with-Run-AI-.md' : 'Administrator/Researcher-Setup/docker-to-runai.md'
        'Researcher/cli-reference/runai-get.md' : 'Researcher/cli-reference/runai-describe.md'
markdown_extensions:
  - codehilite
  - admonition
  - attr_list

  - toc:
      permalink: True
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/runailabs
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/runailabs/

nav:
  - Home: 
    - 'Overview': 'index.md'
    - 'System Components' : 'home/components.md'
    - 'Whats New' : 'home/whats-new.md'
  - 'Administrator' :
    - 'Overview' : 'Administrator/overview-administrator.md'
    - 'Cluster Setup' :
      - 'Introduction' : 'Administrator/Cluster-Setup/cluster-setup-intro.md'
      - 'Prerequisites' : 'Administrator/Cluster-Setup/cluster-prerequisites.md'
      - 'Quick Single Node Install' : 'Administrator/Cluster-Setup/single-node-install.md'
      - 'Cluster Install' : 'Administrator/Cluster-Setup/cluster-install.md'
      - 'Cluster Upgrade' : 'Administrator/Cluster-Setup/cluster-upgrade.md'
      - 'Cluster Delete' : 'Administrator/Cluster-Setup/cluster-delete.md'
      - 'Troubleshooting' : 'Administrator/Cluster-Setup/cluster-troubleshooting.md'
      - ' Kubernetes Install' : 'Administrator/Cluster-Setup/install-k8s.md'      
      - 'Advanced' :
        - 'Allow external access to Containers' : 'Administrator/Cluster-Setup/allow-external-access-to-containers.md'
        - 'Add an Internet Proxy Server ' : 'Administrator/Cluster-Setup/proxy-server.md'
        - 'Authentication and Authorization' : 'Administrator/Cluster-Setup/researcher-authentication.md'
        - 'Limit Install to Specific Nodes' : 'Administrator/Cluster-Setup/limit-runai-install-to-specific-nodes.md'
        - 'Enforce non-root Containers' : 'Administrator/Cluster-Setup/enforce-run-as-user.md'
        - 'Kubernetes Best Practices' : 'Administrator/Cluster-Setup/kubernetes-config-best-practices.md'
        - 'Configure NFS' : 'Administrator/Cluster-Setup/nfs-install.md'
        - 'Node Downtime' : 'Administrator/Cluster-Setup/node-downtime.md'
    - 'Researcher Setup' :
      - 'Introduction' : 'Administrator/Researcher-Setup/researcher-setup-intro.md'
      - 'Install the CLI' : 'Administrator/Researcher-Setup/cli-install.md'
      - 'Troubleshooting' : 'Administrator/Researcher-Setup/cli-troubleshooting.md'
      - 'Use a Private Docker Registry' : 'Administrator/Researcher-Setup/docker-registry-config.md'
      - 'Switch from Docker to Run:AI ' : 'Administrator/Researcher-Setup/docker-to-runai.md'
      - 'Limit Run:AI to Specific Nodes' : 'Administrator/Researcher-Setup/limit-to-node-group.md'
#      - 'Limit Run:AI to Specific GPUs' : 'Administrator/Researcher-Setup/limit-to-gpus-in-nodes.md'
      - 'Use Secrets in Jobs' : 'Administrator/Researcher-Setup/use-secrets.md'
      - 'Configure Command-Line Interface Templates' : 'Administrator/Researcher-Setup/template-config.md'
    - 'Admin UI Setup' :
      - 'Users' : 'Administrator/Admin-User-Interface-Setup/Adding-Updating-and-Deleting-Admin-UI-Users.md'
      - 'Projects' : 'Administrator/Admin-User-Interface-Setup/Working-with-Projects.md'
      - 'Departments' : 'Administrator/Admin-User-Interface-Setup/Working-with-Departments.md'
    - 'Presentations' :
      - 'Administrator Onboarding' : 'Administrator/Presentations/Administrator-Onboarding-Presentation.md'
    - 'Tools' :
      - 'Submit workloads via YAML' : 'Administrator/tools/launch-job-via-yaml.md'
      - 'Submit workloads via Rancher' : 'Administrator/tools/Launch-Workloads-using-Rancher-User-Interface.md' 
      - 'Airflow integration' : 'Administrator/tools/airflow-integration.md' 
  - 'Researcher' :
    - 'Overview' : 'Researcher/overview-researcher.md'
    - 'Quickstart Guides' :
      - 'Run:AI Quickstart Guides' : 'Researcher/Walkthroughs/Run-AI-Walkthroughs.md'
      - 'Training' : 'Researcher/Walkthroughs/walkthrough-train.md'
      - 'Build' : 'Researcher/Walkthroughs/walkthrough-build.md'
      - 'Build with Connected Ports' : 'Researcher/Walkthroughs/walkthrough-build-ports.md'
#      - 'GPU Fractions' : 'Researcher/Walkthroughs/walkthrough-fractions.md'
      - 'Distributed Training Workloads' : 'Researcher/Walkthroughs/walkthrough-distributed-training.md'
      - 'Hyperparameter Optimization' : 'Researcher/Walkthroughs/walkthrough-hpo.md'
      - 'Over-Quota, Basic Fairness & Bin-Packing' : 'Researcher/Walkthroughs/walkthrough-overquota.md'
      - 'Queue Fairness' : 'Researcher/Walkthroughs/walkthrough-queue-fairness.md'
      - 'Elasticity' : 'Researcher/Walkthroughs/walkthrough-elasticity.md'
    - 'CLI Reference' :
      - 'Introduction' : 'Researcher/cli-reference/Introduction.md'
      - 'runai attach' : 'Researcher/cli-reference/runai-attach.md'
      - 'runai bash' : 'Researcher/cli-reference/runai-bash.md'
      - 'runai cluster' : 'Researcher/cli-reference/runai-cluster.md'
      - 'runai config' : 'Researcher/cli-reference/runai-config.md'
      - 'runai delete' : 'Researcher/cli-reference/runai-delete.md'
      - 'runai describe' : 'Researcher/cli-reference/runai-describe.md'
      - 'runai exec' : 'Researcher/cli-reference/runai-exec.md'
      - 'runai list' : 'Researcher/cli-reference/runai-list.md'
      - 'runai logs' : 'Researcher/cli-reference/runai-logs.md'
      - 'runai project' : 'Researcher/cli-reference/runai-project.md'
      - 'runai submit' : 'Researcher/cli-reference/runai-submit.md'
      - 'runai submit-mpi' : 'Researcher/cli-reference/runai-submit-mpi.md'
      - 'runai template' : 'Researcher/cli-reference/runai-template.md'
      - 'runai top node' : 'Researcher/cli-reference/runai-top-node.md'
      - 'runai update' : 'Researcher/cli-reference/runai-update.md'
      - 'runai version' : 'Researcher/cli-reference/runai-version.md'
    - 'Best Practices' :
      - 'Bare-Metal to Docker Images' : 'Researcher/best-practices/From-Bare-Metal-to-using-Docker-Images.md'
      - 'Convert a Workload to Run Unattended' : 'Researcher/best-practices/convert-to-unattended.md'
      - 'Save Deep Learning Checkpoints' : 'Researcher/best-practices/Saving-Deep-Learning-Checkpoints.md'
      - 'Identify a Job from within Container' : 'Researcher/best-practices/env-variables.md'
    - 'Scheduling' :
      - 'Allocation of CPU and Memory' : 'Researcher/Scheduling/Allocation-of-CPU-and-Memory.md'
      - 'The Run:AI Scheduler' : 'Researcher/Scheduling/The-Run-AI-Scheduler.md'
      - 'Job Statuses' : 'Researcher/Scheduling/Job-Statuses.md'
      - 'Automatically Delete Finished Workloads' : 'Researcher/Scheduling/auto-delete-jobs.md'
    - 'Researcher Library' :
      - 'Overview' : 'Researcher/researcher-library/researcher-library-overview.md'
      - 'Elasticity' : 'Researcher/researcher-library/rl-elasticity.md'
      - 'Reporting' : 'Researcher/researcher-library/rl-reporting.md'
      - 'HPO' : 'Researcher/researcher-library/rl-hpo-support.md'
    - 'Presentations' :
      - 'Researcher Onboarding' : 'Researcher/Presentations/Researcher-Onboarding-Presentation.md'
    - 'Tools' :
      - 'Visual Studio Code' : 'Researcher/tools/dev-vscode.md'    
      - 'PyCharm' : 'Researcher/tools/dev-pycharm.md'    
      - 'X11 & PyCharm' : 'Researcher/tools/dev-x11forward-pycharm.md'  
      - 'Jupyter Noteook' :  'Researcher/tools/dev-jupyter.md'
      - 'TensorBoard' :  'Researcher/tools/dev-tensorboard.md'
  - 'Community Edition' :
     - 'Overview' : 'community/overview.md'
     - 'Installation' : 'community/install.md'
     - 'Reference' : 'community/flags.md'
     - 'Environment Variables' : 'community/env.md'
      

